# Generated by Django 5.2.5 on 2025-11-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='credited',
            field=models.BooleanField(default=False),
        ),
    ]
