# Generated by Django 5.2.5 on 2025-11-09 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionprice',
            name='effective_from',
        ),
        migrations.RemoveField(
            model_name='adoptionprice',
            name='effective_to',
        ),
        migrations.RemoveField(
            model_name='adoptionprice',
            name='is_active',
        ),
    ]
