# Generated by Django 5.2.5 on 2025-08-22 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pet', '0001_initial'),
        ('authuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='keeper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kept_pets', to='authuser.user'),
        ),
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_pets', to='authuser.user'),
        ),
    ]
