# Generated by Django 5.2.5 on 2025-11-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0002_remove_adoptionprice_effective_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='adoption_days',
            field=models.PositiveIntegerField(default=1, help_text='Number of days this pet is listed for adoption'),
        ),
    ]
