# Generated by Django 5.2.5 on 2025-11-07 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0003_category_pet_deleted_at_pet_is_deleted_adoptionprice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='is_deleted',
        ),
    ]
