# Generated by Django 5.2.5 on 2025-11-14 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_order_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppayment',
            name='credited',
        ),
        migrations.RemoveField(
            model_name='shoppayment',
            name='raw_response',
        ),
        migrations.RemoveField(
            model_name='shoppayment',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='shoppayment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='shoppayment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='shoppayment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shoppayment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='shop.order'),
        ),
    ]
